[[language]]
name = "python"
formatter = { command = "black", args = ["--quiet", "-"] }
auto-format = true
config = {pylsp={plugins={pycodestyle={enabled=false},flake8={enabled=true,maxLineLength=120},pyflakes={enabled=false}}}}
#config = {pylsp={plugins={flake8={enabled=true, maxLineLength=88}}}}
