# [[language]]
# name = "python"
# formatter = { command = "black", args = ["--quiet", "-"] }
# auto-format = true
# text-width = 120

[[language]]
name = "python"
scope = "source.python"
injection-regex = "python"
file-types = ["py","pyi","py3","pyw","ptl",".pythonstartup",".pythonrc","SConstruct"]
shebangs = ["python"]
roots = []
comment-token = "#"
language-servers = [ "pylsp" ]
formatter = { command = "black", args = ["--quiet", "-l", "120", "-"] }
auto-format = true
text-width = 120

# TODO: pyls needs utf-8 offsets
indent = { tab-width = 4, unit = "    " }

[language-server.pylsp.config.plugins]
flake8 = {enabled = true, maxLineLength=120}
autopep8 = {enabled = false}
mccabe = {enabled = false}
pycodestyle = {enabled = false}
pyflakes = {enabled = false}
pylint = {enabled = false}
yapf = {enabled = false}
# ruff = { enabled = true, ignore = ["F401"], lineLength = 120 }
# config = {pylsp={plugins={pycodestyle={enabled=false},flake8={enabled=true,maxLineLength=120},pyflakes={enabled=false}}}}
#config = {pylsp={plugins={flake8={enabled=true, maxLineLength=88}}}}
